name: XRay-Images
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.4.0
  - torchvision=0.5.0
  - cudatoolkit=10.1.243
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.3.1
  - pandas=1.0.1
  - numpy=1.18.1
  - matplotlib=3.1.1
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.2.5
  - jupyterlab_server=1.0.6
  - ipykernel=5.1.3
  - pip=19.3.1
  - pip:
    - albumentations==0.4.5
    - ruamel-yaml==0.16.10
    - pyyaml==5.3.1
    - tqdm==4.45.0
    - imgaug==0.2.6
    - qtconsole==4.7.2
    - qtpy==1.9.0
    