default: &DEFAULT
  num_epochs: 1000
  batch_size: 256


CNN:
  <<: *DEFAULT
  model_name: cnn
  data_dir: "../Datasets/chest_xray"
  checkpoint_dir: "checkpoints/cnn"
  log_dir: 'logs/cnn'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 16
  augments_train: CNN_Train_Augments
  augments_val: CNN_Eval_Augments
  net_args: {}
  lr: 0.0001

AlexNet:
  <<: *DEFAULT
  model_name: alexnet
  data_dir: "../Datasets/chest_xray"
  checkpoint_dir: "checkpoints/alexnet"
  log_dir: 'logs/alexnet'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 16
  augments_train: AlexNet_Train_Augments
  augments_val: AlexNet_Eval_Augments
  net_args: {}
  lr: 0.0001

ResNext:
  <<: *DEFAULT
  model_name: resnext
  data_dir: "../Datasets/chest_xray"
  checkpoint_dir: "checkpoints/resnext"
  log_dir: 'logs/resnext'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 16
  augments_train: ResNext_Train_Augments
  augments_val: ResNext_Eval_Augments
  net_args: {freeze_layers: True}
  lr: 0.0001
