default: &DEFAULT
  num_epochs: 1000
  batch_size: 256


CNN:
  <<: *DEFAULT
  model_name: cnn
  data_dir: "chest_xray"
  checkpoint_dir: "checkpoints/cnn"
  log_dir: 'logs/cnn'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 16
  transforms: CNN_Transforms
  lr: 0.0001
