default: &DEFAULT
  num_epochs: 1000
  batch_size: 256


CNN:
  <<: *DEFAULT
  model_name: cnn
  data_dir: "../Datasets/chest_xray"
  checkpoint_dir: "checkpoints/cnn"
  log_dir: 'logs/cnn'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 16
  transforms_train: CNN_Train_Transforms
  transforms_val: CNN_Eval_Transforms
  net_args: {}
  lr: 0.0001

AlexNet:
  <<: *DEFAULT
  model_name: alexnet
  data_dir: "../Datasets/chest_xray"
  checkpoint_dir: "checkpoints/alexnet"
  log_dir: 'logs/alexnet'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 16
  transforms_train: AlexNet_Train_Transforms
  transforms_val: AlexNet_Eval_Transforms
  net_args: {}
  lr: 0.0001

ResNext:
  <<: *DEFAULT
  model_name: resnext
  data_dir: "../Datasets/chest_xray"
  checkpoint_dir: "checkpoints/resnext"
  log_dir: 'logs/resnext'
  dataset_class: "XRayDataset"
  gpu_vis_dev: '0'
  num_epochs: 2
  batch_size: 4
  transforms_train: ResNext_Train_Transforms
  transforms_val: ResNext_Eval_Transforms
  net_args: {freeze_layers: True}
  lr: 0.0001
